version: 0.2

env:
  parameter-store: # securely pass variables in the build project
    SECRET_ID: "ACCESS_KEY_ID"
    SECRET_KEY: "SECRET_ACCESS_KEY"
    SECRET_NAME: "PROFILE_NAME"
    SECRET_REGION: "Region" 
    
phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - cd cicd 
      - chmod +x install-terraform.sh configure-named-profile.sh apply-terraform.sh # make files executable
      - ./install-terraform.sh # install terraform
      - ./configure-named-profile.sh # configure named profile

  build:
    commands:
      - ./apply-terraform.sh