version: 0.2

env:
  parameter-store:
    - SECRET_TOKEN: "ACCESS_KEY_ID"
    - SECRET_TOKEN: "SECRET_ACCESS_KEY"
    - SECRET_TOKEN: "PROFILE_NAME"
    - SECRET_TOKEN: "Region" 
    
phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - cd cicd # change directory
      - chmod +x install-terraform.sh configure-named-profile.sh apply-terraform.sh # make files executable
      - ./install-terraform.sh # install terraform
      - ./configure-named-profile.sh # configure named profile

  build:
    commands:
      - ./apply-terraform.sh