name: DEPLOY AWS RESOURCES

on: 
  push:
    branches:
      - "main"

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Deploy AWS Resources
    defaults: 
      run:
        working-directory: grants-website-ecs
    steps:
    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2     # default
        verbose: false # default
        arch: amd64    # allowed values: amd64, arm64
        rootdir: ""    # defaults to "PWD"
        workdir: ""    # defaults to "PWD/unfor19-awscli"
        
    - name: Checkout
      uses: actions/checkout@v2     

    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
          version: 0.13.4

    - name: terraform plan
      run: |
        terraform init
        terraform plan
