variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public_subnet1_cidr" {}
variable "public_subnet2_cidr" {}
variable "private_app_subnet1_cidr" {}
variable "private_app_subnet2_cidr" {}
variable "private_data_subnet1_cidr" {}
variable "private_data_subnet2_cidr" {}
variable "domain_name" {}
variable "alternative_name" {}
variable "container_image" {}